### PR TITLE
fix: failure when config from view to Iceberg table

### LINKED ISSUE #366: Switching a model from view to Iceberg table fails
dbt-athena 1.5.1

Given a view model
When I change the config to an Iceberg table
Then the dbt run fails with the following error

```
ERROR    stdout_log:eventmgr.py:66 16:53:09  Runtime Error in model model_mc_modelface (models/model_mc_modelface.sql)
ERROR    file_log:eventmgr.py:66 17:53:09.695792 [error] [MainThread]: Runtime Error in model model_mc_modelface (models/model_mc_modelface.sql)
ERROR    stdout_log:eventmgr.py:66 16:53:09    [ErrorCategory:USER_ERROR, ErrorCode:DDL_FAILED], Detail:FAILED: ParseException line 1:87 cannot recognize input near '.' 'model_mc_modelface' 'rename' in alter table statement
ERROR    file_log:eventmgr.py:66 17:53:09.697794 [error] [MainThread]:   [ErrorCategory:USER_ERROR, ErrorCode:DDL_FAILED], Detail:FAILED: ParseException line 1:87 cannot recognize input near '.' 'model_mc_modelface' 'rename' in alter table statement
```

I think it's not checking whether the old relation was a view and issuing a table rename which then fails. Tests and fix incoming...

### PR DESCRIPTION
**Pull request by brabster**
### Description

resolve #366

## Models used to test - Optional
standard base tests

## Checklist
- [/] You followed [contributing section](https://github.com/dbt-athena/dbt-athena#contributing)
- [/] You kept your Pull Request small and focused on a single feature or bug fix.
- [/] You added unit testing when necessary
- [/] You added functional testing when necessary

### CODE REVIEW

**Comment by brabster** [comment]
New tests passing, rest of suite passing - ready for review

File: dbt/include/athena/macros/materializations/models/table/table.sql [hunk 1]
```diff
@@ -82,27 +82,36 @@
...
-      {%- set old_relation_bkp = make_temp_relation(old_relation, '__bkp') -%}
-      -- If we have this, it means that at least the first renaming occurred but there was an issue
-      -- afterwards, therefore we are in weird state. The easiest and cleanest should be to remove
-      -- the backup relation. It won't have an impact because since we are in the else condition,
-      -- that means that old relation exists therefore no downtime yet.
-      {%- if old_relation_bkp is not none -%}
-        {%- do drop_relation(old_relation_bkp) -%}
+      {%- if old_relation.is_view -%}
+        {%- call statement('main') -%}
+          {{ create_table_as(False, tmp_relation, sql) }}
```
Comment (nicor88) [inline dbt/include/athena/macros/materializations/models/table/table.sql:87]: why not using `{{ create_table_as(False, target_relation, sql) }}` and avoid the final rename?

**Review by nicor88 — APPROVED** [review]
Thanks @brabster to cover this edge case, @Jrmyy do you want to have another look?

**Review by Jrmyy — APPROVED** [review]
