### PR TITLE
fix: docs generate support federated query catalogs

### LINKED ISSUE #306: Error running dbt docs generate with Federated Query database
I'm trying to run `dbt docs generate` with Federated Query data using the Redshift Connector and it returns the following error:

```
[0m15:45:16.272788 [debug] [ThreadPool]: Acquiring new athena connection 'awsdatacatalog.information_schema'
[0m15:45:16.273878 [debug] [ThreadPool]: Acquiring new athena connection 'redshiftCatalog_dev.information_schema'
[0m15:45:16.274842 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m15:45:16.275793 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m15:45:17.416799 [debug] [ThreadPool]: On redshiftCatalog_dev.information_schema: Close
[0m15:45:17.419386 [warn ] [MainThread]: Encountered an error while generating catalog: 'catalog-id'
[0m15:45:20.555092 [debug] [ThreadPool]: On awsdatacatalog.information_schema: Close
[0m15:45:20.707223 [error] [MainThread]: dbt encountered 1 failure while writing the catalog
[0m15:45:20.709353 [info ] [MainThread]: Catalog written to /app/target/catalog.json
```

I'm aware of #247 but believe this is an issue with using non-glue data catalogs.

The catalog file and html are generated and aparently look fine, but the error is returned nonetheless.

### PR DESCRIPTION
**Pull request by maiarareinaldo**
### Description

Resolve #306 

Updated `_get_one_catalog` to use Glue API only if catalog is of type `GLUE`, otherwise it runs the `get_catalog` macro which was changed back to query information_schema.

## Checklist
- [ ] You followed [contributing section](https://github.com/dbt-athena/dbt-athena#contributing)
- [ ] You kept your Pull Request small and focused on a single feature or bug fix.
- [ ] You added unit testing when necessary
- [ ] You added functional testing when necessary

### CODE REVIEW

File: dbt/include/athena/macros/adapters/metadata.sql [hunk 1]
```diff
@@ -1,6 +1,89 @@
 {% macro athena__get_catalog(information_schema, schemas) -%}
-    {{ return(adapter.get_catalog()) }}
-{%- endmacro %}
+  {%- set query -%}
```
Comment (Jrmyy) [inline dbt/include/athena/macros/adapters/metadata.sql:2]: If you set this, this will not call the adapter function defined in Python or I am missing something ? 🤔

Comment (maiarareinaldo) [reply dbt/include/athena/macros/adapters/metadata.sql:2]: From what I understood the adapter function is called first from the docs generate task [here](https://github.com/dbt-labs/dbt-core/blob/45d614533f0c7de81e20488c75c707262c9312e1/core/dbt/task/generate.py#L240), so the order of invocation goes `generate -> adapter.get_catalog -> adapter._get_one_catalog -> get_catalog macro`. So the macro doesn't call the adapter function, is actually the other way around. The only place I found where the `get_catalog` macro is executed was [here](https://github.com/dbt-labs/dbt-core/blob/45d614533f0c7de81e20488c75c707262c9312e1/core/dbt/adapters/base/impl.py#L1069) on the base adapter `_get_one_catalog` function which is overwritten by the Athena adapter anyway.

Comment (Jrmyy) [reply dbt/include/athena/macros/adapters/metadata.sql:2]: Ok, I check and it seems like that, good to know :)

File: tests/unit/test_adapter.py [hunk 2]
```diff
@@ -612,9 +650,65 @@ def test__get_one_catalog_shared_catalog(self, mock_aws_service):
         for row in actual.rows.values():
             assert row.values() in expected_rows
 
+    @mock_athena
+    @mock.patch.object(AthenaAdapter, "execute_macro")
+    def test__get_one_catalog_federated_query_catalog(self, mock_execute, mock_aws_service):
```
[the remark this answers is not in the document]
Comment (maiarareinaldo) [reply tests/unit/test_adapter.py:655]: I think this is already kind of being tested as I only use mock_glue when the glue api is called. Also moto is being used to mock glue and I don't think it supports anything like `assert_called` or `.called`, CMIIW but I couldn't find anything.

**Comment by Jrmyy** [comment]
@svdimchenko can you also take a look as a second pair of eyes please ? 😇

File: dbt/adapters/athena/impl.py [hunk 3]
```diff
@@ -385,28 +386,38 @@ def _get_one_catalog(
...
-            }
-            # If the catalog is `awsdatacatalog` we don't need to pass CatalogId as boto3 infers it from the account Id.
-            if catalog_id:
-                kwargs["CatalogId"] = catalog_id
 
-            for page in paginator.paginate(**kwargs):
-                for table in page["TableList"]:
-                    if table["Name"] in relations:
-                        catalog.extend(self._get_one_table_for_catalog(table, information_schema.path.database))
+        if data_catalog["Type"] == "GLUE":
```
Comment (svdimchenko) [inline dbt/adapters/athena/impl.py:390]: great work done, the code looks good to me. However I have a question. According to the [AWS doc](https://docs.aws.amazon.com/athena/latest/APIReference/API_DataCatalog.html) there are 3 possible options for catalog type: `GLUE`, `HIVE` and `LAMBDA`. You have implemented `LAMBDA` case I guess. If it's so, let's add kind of Enum for CatalogTypes and at least log warning or raise a NotImplemented error for HIVE catalog type

File: dbt/adapters/athena/impl.py [hunk 4]
```diff
@@ -385,28 +386,38 @@ def _get_one_catalog(
     ) -> agate.Table:
         data_catalog = self._get_data_catalog(information_schema.path.database)
         catalog_id = get_catalog_id(data_catalog)
```
Comment (svdimchenko) [inline dbt/adapters/athena/impl.py:388]: it seems `catalog_id` has no sense for non GLUE catalogues. Let's put this call after 
```
if data_catalog["Type"] == "GLUE":
```

File: dbt/include/athena/macros/adapters/metadata.sql (hunk 1 above)
Comment (svdimchenko) [reply dbt/include/athena/macros/adapters/metadata.sql:2]: I'm wondered if AWS does not provide possibility to get data catalog details (databases, tables, columns) programmatically for non GLUE catalog types. Just after quick look at their doc I see that CatalogId parameter is required for such API calls, but as I understand we can not get catalog-id ? Did I miss smth ?

File: tests/unit/utils.py [hunk 5]
```diff
@@ -149,7 +149,10 @@ def create_data_catalog(
         self, catalog_name: str = DATA_CATALOG_NAME, catalog_type: str = "GLUE", catalog_id: str = CATALOG_ID
     ):
         athena = boto3.client("athena", region_name=AWS_REGION)
-        athena.create_data_catalog(Name=catalog_name, Type=catalog_type, Parameters={"catalog-id": catalog_id})
+        parameters = {}
+        if catalog_type == "GLUE":
```
Comment (svdimchenko) [inline tests/unit/utils.py:153]: let's now use `AthenaCatalogType` enum instead of constants everywhere

File: dbt/adapters/athena/utils.py [hunk 6]
```diff
@@ -9,7 +10,17 @@ def clean_sql_comment(comment: str) -> str:
 
 
 def get_catalog_id(catalog: Optional[DataCatalogTypeDef]) -> Optional[str]:
-    return catalog["Parameters"]["catalog-id"] if catalog else None
+    return catalog["Parameters"]["catalog-id"] if catalog and catalog["Type"] == "GLUE" else None
+
+
+class AthenaCatalogType(Enum):
```
Comment (svdimchenko) [inline dbt/adapters/athena/utils.py:16]: I think we can create separate module `catalog` and move there all corresponding methods about catalog from here and `impl` module. This will shorten our `impl` module and make adapter a bit more readable. @maiarareinaldo @Jrmyy WDYT can we do it in current PR or do such refactoring in separate one ? `utils` module seems to be not suitable place for such concrete entity as catalog.

File: dbt/adapters/athena/impl.py (hunk 3 above)
Comment (svdimchenko) [reply dbt/adapters/athena/impl.py]: thanks, I've added some minor comments regarding modules structure

File: dbt/adapters/athena/utils.py (hunk 6 above)
Comment (svdimchenko) [reply dbt/adapters/athena/utils.py:16]: all right. then I'll close this thread for now

File: dbt/adapters/athena/utils.py [hunk 7]
```diff
@@ -9,7 +10,17 @@ def clean_sql_comment(comment: str) -> str:
 
 
 def get_catalog_id(catalog: Optional[DataCatalogTypeDef]) -> Optional[str]:
-    return catalog["Parameters"]["catalog-id"] if catalog else None
+    return catalog["Parameters"]["catalog-id"] if catalog and catalog["Type"] == "GLUE" else None
```
Comment (svdimchenko) [inline dbt/adapters/athena/utils.py:13]:
```suggestion
    return catalog["Parameters"]["catalog-id"] if catalog and catalog["Type"] == AthenaCatalogType.GLUE else None
```

**Review by svdimchenko — DISMISSED** [review]

File: dbt/include/athena/macros/adapters/metadata.sql (hunk 1 above)
Comment (Jrmyy) [reply dbt/include/athena/macros/adapters/metadata.sql:2]: @maiarareinaldo sorry I resolved too quickly there is comment left

Comment (maiarareinaldo) [reply dbt/include/athena/macros/adapters/metadata.sql]: hey @svdimchenko, sorry I didn't see your comment before. That's right, for a federated query catalog `get-data-catalog` will return something like this:
```
"DataCatalog": {
    "Name": "catalog_name",
    "Description": "description",
    "Type": "LAMBDA",
    "Parameters": {
        "catalog": "catalog_name",
        "metadata-function": "arn:aws:lambda:<region>:<account_id>:function:<function_name>",
        "record-function": "arn:aws:lambda:<region>:<account_id>:function:<function_name>"
    }
}
```

But you make a very good point, so I looked around and I found this method [list_table_metadata](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/athena/client/list_table_metadata.html) from Athena client. It returns a pretty similar output to Glue get_tables, the only difference being that that it doesn't have a table "Description" key. I'm replacing the query execution with this method for non Glue catalogs. But I wonder if we should actually use it for Glue catalogs as well, which would removed the need for the if-else when getting the catalog details. Please let me know your thoughts.

**Comment by maiarareinaldo** [comment]
hey @Jrmyy, any chance this one could be merged before 1.5.2 release? Not sure when that's planned for. I'm waiting for a second review since addressing this [comment](https://github.com/dbt-athena/dbt-athena/pull/324#discussion_r1223486949).

File: dbt/include/athena/macros/adapters/metadata.sql (hunk 1 above)
Comment (svdimchenko) [reply dbt/include/athena/macros/adapters/metadata.sql]: hi @maiarareinaldo ! I'm so sorry for so long response from my side. Your solution seems good to me.

**Review by svdimchenko — APPROVED** [review]

**Review by Jrmyy — APPROVED** [review]

**Comment by nicor88** [comment]
@maiarareinaldo sorry I totally missed that in the 1.5.2 release - we are planning 1.6.0 release.

@Jrmyy @svdimchenko you had a look already at this one - overall to me seems fine.
Let's see what's the results of the functional tests and eventually merge it.

**Review by nicor88 — APPROVED** [review]
